### ISSUE TITLE
Impossible to animate kPOPLayerRotationY more than 90 degrees

### ISSUE THREAD

**Issue by wircho** [facebook/pop#155] opened 2014-08-25 16:41 UTC
This issue is very simple to reproduce:

    POPBasicAnimation *animation = [POPBasicAnimation animationWithPropertyNamed:kPOPLayerRotationY];
    animation.fromValue = @0;
    animation.toValue = @1.9;
    animation.duration = 1;
    [view.layer pop_addAnimation:animation forKey:@"key"];

**Comment by kimon** [comment] 2015-03-21 21:50
Dupe of https://github.com/facebook/pop/issues/71

**Closed** 2015-03-21 21:51 UTC
Labels: duplicate, enhancement
