### ISSUE TITLE
OSX SDK 10.10 Animation breakage.

### ISSUE THREAD

**Issue by CoreyDotCom** [facebook/pop#230] opened 2015-03-24 12:25 UTC
We recently updated an XCode desktop project from the 10.9 SDK to 10.10 SDK and our pop animations are going pretty nuts.  

We're using a simple animation that animated a custom view property. Upon switching to 10.10 our animations sometimes start over from their initial values.  Very odd.

Has anyone else seen any behavioral changes with 10.10 SDK?

```
    POPBasicAnimation* prev = [self pop_animationForKey:@"zoomFactor"];
    POPBasicAnimation* anim = [POPBasicAnimation defaultAnimation];
    anim.property = [self getZoomPropSpec];
    anim.toValue = @(newValue);
    anim.duration = prev ? 0.1 : .25;
    
    [self pop_addAnimation:anim forKey:@"zoomFactor"];
```

**Comment by CoreyDotCom** [comment] 2015-03-24 13:37
So our animation is triggered by a menu action's keyboard equivalent.  e.g. Command-+ (zoom in)... after researching further it seems that with 10.10 SDK the menu actions block Pop's CVDisplayLink thread so the animation just wasn't actually updating us while a key is held down (a key that is associated with a menu item).   Reverting to 10.9 SDK all is well.  Pretty troubling, but just thought I'd add the info for others that might run into it.

Will file a Radar with Apple.

**Comment by grp** [comment] 2015-05-28 04:58
Interesting, thanks for the report. If you find a way to make the CVDisplayLink run even then, would definitely be good to put in place.

**Comment by CoreyDotCom** [comment] 2015-05-28 12:15
FWIW I was able to work around the issue but they still haven't fixed in the 10.10 SDK. 

Turns out that they are flooding the main GCD queue (which POP uses to dispatch it's animation events off the CVDisplayLink thread).  

I was able to just create my own NSMenu derivative and handle "performKeyEquivalent" for the menu actions that I knew would directly trigger animations (such as Zoom In or Zoom Out).  This worked great.  I am not sure if their action dispatch code was what is busted or if their menu "flash" is the culprit..either way, moving on. :/

**Comment by grp** [comment] 2015-05-28 22:58
Thanks, I'll close this out now since it's not a bug in Pop, but thanks for explaining as a reference.

**Closed by grp** 2015-05-28 22:58 UTC

**Comment by CoreyDotCom** [comment] 2015-05-28 23:10
Well it could be considered a POP bug, I think it was brought up before as well...(that maybe you guys shouldn't be using GCD on main UI thread as the animations always take a back seat)...I can't find the issue but it's in there somewhere.

**Comment by CoreyDotCom** [comment] 2015-05-29 15:13
It was basically this one https://github.com/facebook/pop/issues/193 that predicted the issue way back when. :)

**Comment by grp** [comment] 2015-05-29 18:45
Yeah, Pop fundamentally requires the main thread to be free, on both OS X and iOS.
